AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  Metrics/MethodLength:
    Max: 25

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false
